site_name: Markdown to Confluence
site_url: https://spydersoft-consulting.github.io/md_to_conf/


nav:
  - Home: 'index.md'
  - 'getting-started.md'
  - Markdown :
    - 'Quick Reference': 'markdown-quick-reference.md'
    - 'Syntax': 'markdown-syntax.md'
    - 'Examples': 'markdown-examples.md'
  - Contribute: 'contributing.md'
  - Changes: 'CHANGELOG.md'
  - 'API Documentation':
    - 'api/client-reference.md'
    - 'api/converter-reference.md'
    - 'api/main-reference.md'
  #   - 'api/statuspage_io-reference.md'
  #   - 'api/statuspage_io_client-reference.md'
  #   - 'api/enums.md'

theme:
  name: 'material'

plugins:
  - search
  - mkdocstrings
